#!/bin/bash

echo "" > /home/work3.log

# write all users and their ids to work3.log
echo "Problem 1" >> /home/work3.log

all_users=$(cat /etc/passwd | cut -d: -f1)
for user in $all_users
do
    echo "user $user has id $(id -u $user)" >> /home/work3.log
done

# add last change date to work3.log
echo "Problem 2" >> /home/work3.log

user=root
date=$(chage -l $user | head -1| cut -d: -f2)
echo "date of last password change for user $user is $date" >> /home/work3.log

# add all groups to work3.log
echo "Problem 3" >> /home/work3.log

all_groups=$(cat /etc/group | cut -d: -f1)
echo "$(awk '{print $0}' ORS="," <<< "$all_groups" | sed 's/,$//')" >> /home/work3.log

# add hello file
echo "Be careful!" > /etc/skel/readme.txt

# add new user
useradd -m -p $(openssl passwd -1 12345678) u1

# add new group
groupadd g1

# add user to group
usermod -a -G g1 u1

# add u1 user info
echo "Problem 8" >> /home/work3.log

user=u1
echo "user $user has id $(id -u $user) and belongs to groups $(id -Gn $user)" >> /home/work3.log

# include user(mokaruuns) to u1 group
user=mokaruuns
usermod -a -G g1 $user

# add info about g1 group
echo "Problem 10" >> /home/work3.log

group=g1
echo "$(awk '{print $0}' ORS="," <<< "$(cat /etc/group | grep $group | cut -d: -f4)" | sed 's/,$//')" >> /home/work3.log

# add mc to u1 user
user=u1
# echo "/usr/bin/mc" >> /home/$user/.bash_profile
usermod -s /usr/bin/mc $user

# create new user u2 with password 87654321
useradd -m -p $(openssl passwd -1 87654321) u2

# copy work3.log
mkdir /home/test13
cp /home/work3.log /home/test13/work3-1.log
cp /home/work3.log /home/test13/work3-2.log

# set permissions
groupadd group13
usermod -a -G group13 u1
usermod -a -G group13 u2
chown -R u1:group13 /home/test13
chmod -R 640 /home/test13

# create test14
mkdir /home/test14
chmod +t /home/test14
chown u1:u1 /home/test14

# copy test14
cp /usr/bin/nano /home/test14/nano
chown u1:u1 /home/test14/nano
chmod u+s /home/test14/nano

# create test15
mkdir /home/test15
echo "secret file"  > /home/test15/.secret_file
chmod 111 /home/test15
chmod 444 /home/test15/.secret_file
